// <auto-generated />
using System;
using FIAPCloudGames.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIAPCloudGames.Data.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20251221185527_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContato"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdContato");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contato", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdEndereco");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Game", b =>
                {
                    b.Property<Guid>("IdGame")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRelease")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desenvolvedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdGame");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioGameBiblioteca", b =>
                {
                    b.Property<Guid>("IdUsuarioGame")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoAquisicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoAquisicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioGame");

                    b.HasIndex("GameId");

                    b.HasIndex("UsuarioId", "GameId")
                        .IsUnique();

                    b.ToTable("UsuarioGameBiblioteca", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("IdUsuarioPerfil")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioPerfil");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("UsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioRole", b =>
                {
                    b.Property<Guid>("IdUsuarioRole")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioRole");

                    b.HasIndex("RoleId");

                    b.HasIndex("UsuarioId", "RoleId")
                        .IsUnique();

                    b.ToTable("UsuarioRole", (string)null);
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Contato", b =>
                {
                    b.HasOne("FIAPCloudGames.Domain.Models.Usuario", "Usuario")
                        .WithMany("Contatos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Endereco", b =>
                {
                    b.HasOne("FIAPCloudGames.Domain.Models.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioGameBiblioteca", b =>
                {
                    b.HasOne("FIAPCloudGames.Domain.Models.Game", "Game")
                        .WithMany("Biblioteca")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIAPCloudGames.Domain.Models.Usuario", "Usuario")
                        .WithMany("Biblioteca")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("FIAPCloudGames.Domain.Models.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("FIAPCloudGames.Domain.Models.UsuarioPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.UsuarioRole", b =>
                {
                    b.HasOne("FIAPCloudGames.Domain.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FIAPCloudGames.Domain.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Game", b =>
                {
                    b.Navigation("Biblioteca");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FIAPCloudGames.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Biblioteca");

                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");

                    b.Navigation("Perfil")
                        .IsRequired();

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
