// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FIAPCloudGames.BDD.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeEnderecosFeature : object, Xunit.IClassFixture<GerenciamentoDeEnderecosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "EnderecoAppService.feature"
#line hidden
        
        public GerenciamentoDeEnderecosFeature(GerenciamentoDeEnderecosFeature.FixtureData fixtureData, FIAPCloudGames_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Endereços", "    Como um usuário do sistema\r\n    Eu quero gerenciar meus endereços\r\n    Para m" +
                    "anter minhas informações de endereço atualizadas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
    testRunner.Given("que o serviço de endereços está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar endereços de um usuário existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Listar endereços de um usuário existente")]
        public void ListarEnderecosDeUmUsuarioExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar endereços de um usuário existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 14
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 15
    testRunner.And("o usuário possui 2 endereços cadastrados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.When("eu listar os endereços do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 17
    testRunner.Then("a listagem de endereços deve retornar 2 endereços", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 18
    testRunner.And("todos os endereços devem pertencer ao usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar endereços de um usuário sem endereços")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Listar endereços de um usuário sem endereços")]
        public void ListarEnderecosDeUmUsuarioSemEnderecos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar endereços de um usuário sem endereços", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 21
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 22
    testRunner.And("o usuário não possui endereços cadastrados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 23
    testRunner.When("eu listar os endereços do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 24
    testRunner.Then("a listagem de endereços deve retornar 0 endereços", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao listar endereços de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao listar endereços de usuário inexistente")]
        public void FalhaAoListarEnderecosDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao listar endereços de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 27
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 28
    testRunner.When("eu listar os endereços do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 29
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 30
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar endereço com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Cadastrar endereço com sucesso")]
        public void CadastrarEnderecoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar endereço com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 35
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table7.AddRow(new string[] {
                            "Rua",
                            "Rua das Flores"});
                table7.AddRow(new string[] {
                            "Numero",
                            "123"});
                table7.AddRow(new string[] {
                            "Complemento",
                            "Apto 45"});
                table7.AddRow(new string[] {
                            "Bairro",
                            "Centro"});
                table7.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table7.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table7.AddRow(new string[] {
                            "Cep",
                            "01310-100"});
#line 36
    testRunner.And("tenho os dados do endereço:", ((string)(null)), table7, "E ");
#line hidden
#line 45
    testRunner.When("eu cadastrar o endereço para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 46
    testRunner.Then("o endereço deve ser cadastrado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 47
    testRunner.And("o endereço retornado deve ter um ID válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 48
    testRunner.And("o endereço deve conter os dados informados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar endereço sem complemento")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Cadastrar endereço sem complemento")]
        public void CadastrarEnderecoSemComplemento()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar endereço sem complemento", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 51
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table8.AddRow(new string[] {
                            "Rua",
                            "Avenida Paulista"});
                table8.AddRow(new string[] {
                            "Numero",
                            "1000"});
                table8.AddRow(new string[] {
                            "Bairro",
                            "Bela Vista"});
                table8.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table8.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table8.AddRow(new string[] {
                            "Cep",
                            "01310-100"});
#line 52
    testRunner.And("tenho os dados do endereço sem complemento:", ((string)(null)), table8, "E ");
#line hidden
#line 60
    testRunner.When("eu cadastrar o endereço para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 61
    testRunner.Then("o endereço deve ser cadastrado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 62
    testRunner.And("o complemento deve ser nulo ou vazio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao cadastrar endereço para usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao cadastrar endereço para usuário inexistente")]
        public void FalhaAoCadastrarEnderecoParaUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao cadastrar endereço para usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 65
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table9.AddRow(new string[] {
                            "Rua",
                            "Rua das Flores"});
                table9.AddRow(new string[] {
                            "Numero",
                            "123"});
                table9.AddRow(new string[] {
                            "Complemento",
                            "Apto 45"});
                table9.AddRow(new string[] {
                            "Bairro",
                            "Centro"});
                table9.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table9.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table9.AddRow(new string[] {
                            "Cep",
                            "01310-100"});
#line 66
    testRunner.And("tenho os dados do endereço:", ((string)(null)), table9, "E ");
#line hidden
#line 75
    testRunner.When("eu cadastrar o endereço para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 76
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 77
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para cadastrar o endereço\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao cadastrar endereço quando serviço retorna null")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao cadastrar endereço quando serviço retorna null")]
        public void FalhaAoCadastrarEnderecoQuandoServicoRetornaNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao cadastrar endereço quando serviço retorna null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 80
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 81
    testRunner.And("o serviço de endereço não consegue cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table10.AddRow(new string[] {
                            "Rua",
                            "Rua das Flores"});
                table10.AddRow(new string[] {
                            "Numero",
                            "123"});
                table10.AddRow(new string[] {
                            "Complemento",
                            "Apto 45"});
                table10.AddRow(new string[] {
                            "Bairro",
                            "Centro"});
                table10.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table10.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table10.AddRow(new string[] {
                            "Cep",
                            "01310-100"});
#line 82
    testRunner.And("tenho os dados do endereço:", ((string)(null)), table10, "E ");
#line hidden
#line 91
    testRunner.When("eu cadastrar o endereço para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 92
    testRunner.Then("deve lançar uma exceção de domínio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 93
    testRunner.And("a mensagem deve ser \"Não foi possível cadastrar o endereço. Verifique os dados fo" +
                        "rnecidos.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar endereço com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Atualizar endereço com sucesso")]
        public void AtualizarEnderecoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar endereço com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 97
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 98
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 99
    testRunner.And("existe um endereço com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table11.AddRow(new string[] {
                            "Rua",
                            "Rua Nova"});
                table11.AddRow(new string[] {
                            "Numero",
                            "456"});
                table11.AddRow(new string[] {
                            "Complemento",
                            "Casa"});
                table11.AddRow(new string[] {
                            "Bairro",
                            "Jardim Paulista"});
                table11.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table11.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table11.AddRow(new string[] {
                            "Cep",
                            "01405-000"});
#line 100
    testRunner.And("tenho os dados atualizados do endereço:", ((string)(null)), table11, "E ");
#line hidden
#line 109
    testRunner.When("eu atualizar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f" +
                        "64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 110
    testRunner.Then("o endereço deve ser atualizado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 111
    testRunner.And("o endereço retornado deve ter os novos dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar endereço de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar endereço de usuário inexistente")]
        public void FalhaAoAtualizarEnderecoDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar endereço de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 114
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table12.AddRow(new string[] {
                            "Rua",
                            "Rua Nova"});
                table12.AddRow(new string[] {
                            "Numero",
                            "456"});
                table12.AddRow(new string[] {
                            "Complemento",
                            "Casa"});
                table12.AddRow(new string[] {
                            "Bairro",
                            "Jardim Paulista"});
                table12.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table12.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table12.AddRow(new string[] {
                            "Cep",
                            "01405-000"});
#line 115
    testRunner.And("tenho os dados atualizados do endereço:", ((string)(null)), table12, "E ");
#line hidden
#line 124
    testRunner.When("eu atualizar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f" +
                        "64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 125
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 126
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para atualizar o endereço\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar endereço inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar endereço inexistente")]
        public void FalhaAoAtualizarEnderecoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar endereço inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 128
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 129
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 130
    testRunner.And("o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" não existe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table13.AddRow(new string[] {
                            "Rua",
                            "Rua Nova"});
                table13.AddRow(new string[] {
                            "Numero",
                            "456"});
                table13.AddRow(new string[] {
                            "Complemento",
                            "Casa"});
                table13.AddRow(new string[] {
                            "Bairro",
                            "Jardim Paulista"});
                table13.AddRow(new string[] {
                            "Cidade",
                            "São Paulo"});
                table13.AddRow(new string[] {
                            "Estado",
                            "SP"});
                table13.AddRow(new string[] {
                            "Cep",
                            "01405-000"});
#line 131
    testRunner.And("tenho os dados atualizados do endereço:", ((string)(null)), table13, "E ");
#line hidden
#line 140
    testRunner.When("eu atualizar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f" +
                        "64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 141
    testRunner.Then("a atualização do endereço deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 142
    testRunner.And("o resultado do endereço deve indicar falha", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar endereço com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Deletar endereço com sucesso")]
        public void DeletarEnderecoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deletar endereço com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 146
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 147
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 148
    testRunner.And("existe um endereço com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 149
    testRunner.When("eu deletar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 150
    testRunner.Then("o endereço deve ser deletado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar endereço de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar endereço de usuário inexistente")]
        public void FalhaAoDeletarEnderecoDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar endereço de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 152
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 153
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 154
    testRunner.When("eu deletar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 155
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 156
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para deletar o endereço\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar endereço inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Endereços")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar endereço inexistente")]
        public void FalhaAoDeletarEnderecoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar endereço inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 158
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 159
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 160
    testRunner.And("o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" não pode ser deletado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 161
    testRunner.When("eu deletar o endereço \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 162
    testRunner.Then("a exclusão do endereço deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeEnderecosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeEnderecosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
