// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FIAPCloudGames.BDD.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeUsuariosFeature : object, Xunit.IClassFixture<GerenciamentoDeUsuariosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UsuarioAppService.feature"
#line hidden
        
        public GerenciamentoDeUsuariosFeature(GerenciamentoDeUsuariosFeature.FixtureData fixtureData, FIAPCloudGames_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Usuários", "    Como um administrador do sistema\r\n    Eu quero gerenciar os usuários\r\n    Par" +
                    "a controlar acessos e informações", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
    testRunner.Given("que o serviço de usuários está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar usuário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Cadastrar usuário com sucesso")]
        public void CadastrarUsuarioComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar usuário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table21.AddRow(new string[] {
                            "Nome",
                            "marcio.silva"});
                table21.AddRow(new string[] {
                            "Senha",
                            "Senha@123"});
                table21.AddRow(new string[] {
                            "Celular",
                            "(11) 98765-4321"});
                table21.AddRow(new string[] {
                            "Email",
                            "marcio@email.com"});
                table21.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva"});
                table21.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table21.AddRow(new string[] {
                            "Pais",
                            "Brasil"});
                table21.AddRow(new string[] {
                            "AvatarUrl",
                            "https://avatar.url"});
#line 14
    testRunner.Given("que tenho os dados do usuário:", ((string)(null)), table21, "Dado ");
#line hidden
#line 24
    testRunner.When("eu cadastrar o usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 25
    testRunner.Then("o usuário deve ser cadastrado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 26
    testRunner.And("o usuário retornado deve ter um ID válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao cadastrar usuário quando serviço retorna null")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Falha ao cadastrar usuário quando serviço retorna null")]
        public void FalhaAoCadastrarUsuarioQuandoServicoRetornaNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao cadastrar usuário quando serviço retorna null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 29
    testRunner.Given("que o serviço de usuário não consegue cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table22.AddRow(new string[] {
                            "Nome",
                            "usuario.invalido"});
                table22.AddRow(new string[] {
                            "Senha",
                            "Senha@123"});
                table22.AddRow(new string[] {
                            "Celular",
                            "(11) 98765-4321"});
                table22.AddRow(new string[] {
                            "Email",
                            "invalido@email.com"});
                table22.AddRow(new string[] {
                            "NomeCompleto",
                            "Usuario Invalido"});
                table22.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table22.AddRow(new string[] {
                            "Pais",
                            "Brasil"});
                table22.AddRow(new string[] {
                            "AvatarUrl",
                            "https://avatar.url"});
#line 30
    testRunner.And("tenho os dados do usuário:", ((string)(null)), table22, "E ");
#line hidden
#line 40
    testRunner.When("eu cadastrar o usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 41
    testRunner.Then("deve lançar uma exceção de domínio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 42
    testRunner.And("a mensagem deve ser \"Não foi possível cadastrar o usuário. Verifique os dados for" +
                        "necidos.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por ID com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Buscar usuário por ID com sucesso")]
        public void BuscarUsuarioPorIDComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar usuário por ID com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 47
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 48
    testRunner.When("eu buscar o usuário por ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 49
    testRunner.Then("o usuário deve ser retornado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 50
    testRunner.And("o usuário deve ter o ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar usuário com perfil e roles")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Buscar usuário com perfil e roles")]
        public void BuscarUsuarioComPerfilERoles()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar usuário com perfil e roles", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 53
    testRunner.Given("que existe um usuário completo com perfil e roles com ID \"3fa85f64-5717-4562-b3fc" +
                        "-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 54
    testRunner.When("eu buscar o usuário por ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 55
    testRunner.Then("o usuário deve ter perfil preenchido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 56
    testRunner.And("o usuário deve ter roles associadas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao buscar usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Falha ao buscar usuário inexistente")]
        public void FalhaAoBuscarUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao buscar usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 59
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 60
    testRunner.When("eu buscar o usuário por ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 61
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 62
    testRunner.And("a mensagem deve ser \"Usuário não encontrado.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar senha com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Alterar senha com sucesso")]
        public void AlterarSenhaComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar senha com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 66
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 67
    testRunner.Given("que existe um usuário para alterar senha com ID \"3fa85f64-5717-4562-b3fc-2c963f66" +
                        "afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 68
    testRunner.When("eu alterar a senha do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\" para \"NovaSe" +
                        "nha@456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 69
    testRunner.Then("a alteração de senha deve ser bem-sucedida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao alterar senha")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Falha ao alterar senha")]
        public void FalhaAoAlterarSenha()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao alterar senha", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 72
    testRunner.Given("que a alteração de senha vai falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 73
    testRunner.When("eu alterar a senha do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\" para \"SenhaI" +
                        "nvalida\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 74
    testRunner.Then("a alteração de senha deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar status do usuário para inativo")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Alterar status do usuário para inativo")]
        public void AlterarStatusDoUsuarioParaInativo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar status do usuário para inativo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 78
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 79
    testRunner.Given("que existe um usuário ativo para alteração de status com ID \"3fa85f64-5717-4562-b" +
                        "3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 80
    testRunner.When("eu alterar o status do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 81
    testRunner.Then("o status deve ser alterado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 82
    testRunner.And("o status retornado deve ser \"Inativo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar status do usuário para ativo")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Alterar status do usuário para ativo")]
        public void AlterarStatusDoUsuarioParaAtivo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar status do usuário para ativo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 85
    testRunner.Given("que existe um usuário inativo para alteração de status com ID \"3fa85f64-5717-4562" +
                        "-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 86
    testRunner.When("eu alterar o status do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 87
    testRunner.Then("o status deve ser alterado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 88
    testRunner.And("o status retornado deve ser \"Ativo\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeUsuariosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeUsuariosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
