// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FIAPCloudGames.BDD.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeRolesDeUsuarioFeature : object, Xunit.IClassFixture<GerenciamentoDeRolesDeUsuarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UsuarioRoleAppService.feature"
#line hidden
        
        public GerenciamentoDeRolesDeUsuarioFeature(GerenciamentoDeRolesDeUsuarioFeature.FixtureData fixtureData, FIAPCloudGames_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Roles de Usuário", "    Como um administrador do sistema\r\n    Eu quero gerenciar as roles dos usuário" +
                    "s\r\n    Para controlar as permissões e acessos de cada usuário", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
    testRunner.Given("que o serviço de usuario role está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Alterar role do usuário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Alterar role do usuário com sucesso")]
        public void AlterarRoleDoUsuarioComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Alterar role do usuário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 14
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 15
    testRunner.And("existe uma role com ID 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.And("existe uma associação usuario-role com ID \"1fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table37.AddRow(new string[] {
                            "TipoUsuario",
                            "Administrador"});
#line 17
    testRunner.And("tenho os dados para alterar a role:", ((string)(null)), table37, "E ");
#line hidden
#line 20
    testRunner.When("eu alterar a role da associação \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário" +
                        " \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 21
    testRunner.Then("a alteração da role deve ser bem-sucedida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao alterar role de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao alterar role de usuário inexistente")]
        public void FalhaAoAlterarRoleDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao alterar role de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 25
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table38.AddRow(new string[] {
                            "TipoUsuario",
                            "Administrador"});
#line 26
    testRunner.And("tenho os dados para alterar a role:", ((string)(null)), table38, "E ");
#line hidden
#line 29
    testRunner.When("eu alterar a role da associação \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário" +
                        " \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 30
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 31
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao alterar para role inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao alterar para role inexistente")]
        public void FalhaAoAlterarParaRoleInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao alterar para role inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 33
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 34
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 35
    testRunner.And("não existe uma role com ID 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 36
    testRunner.And("existe uma associação usuario-role com ID \"1fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table39.AddRow(new string[] {
                            "TipoUsuario",
                            "Administrador"});
#line 37
    testRunner.And("tenho os dados para alterar a role:", ((string)(null)), table39, "E ");
#line hidden
#line 40
    testRunner.When("eu alterar a role da associação \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário" +
                        " \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 41
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 42
    testRunner.And("a mensagem deve conter \"Role com ID 2 não encontrada\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao alterar associação usuario-role inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao alterar associação usuario-role inexistente")]
        public void FalhaAoAlterarAssociacaoUsuario_RoleInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao alterar associação usuario-role inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 45
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 46
    testRunner.And("existe uma role com ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 47
    testRunner.And("não existe uma associação usuario-role com ID \"1fa85f64-5717-4562-b3fc-2c963f66af" +
                        "a6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table40.AddRow(new string[] {
                            "TipoUsuario",
                            "Usuario"});
#line 48
    testRunner.And("tenho os dados para alterar a role:", ((string)(null)), table40, "E ");
#line hidden
#line 51
    testRunner.When("eu alterar a role da associação \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário" +
                        " \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 52
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 53
    testRunner.And("a mensagem deve conter \"Associação Usuário-Role com ID 1fa85f64-5717-4562-b3fc-2c" +
                        "963f66afa6 não encontrada\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao alterar role quando serviço retorna erro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao alterar role quando serviço retorna erro")]
        public void FalhaAoAlterarRoleQuandoServicoRetornaErro()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao alterar role quando serviço retorna erro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 56
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 57
    testRunner.And("existe uma role com ID 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 58
    testRunner.And("existe uma associação usuario-role com ID \"1fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 59
    testRunner.And("o serviço de usuario role não consegue atualizar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table41.AddRow(new string[] {
                            "TipoUsuario",
                            "Administrador"});
#line 60
    testRunner.And("tenho os dados para alterar a role:", ((string)(null)), table41, "E ");
#line hidden
#line 63
    testRunner.When("eu alterar a role da associação \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário" +
                        " \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 64
    testRunner.Then("deve lançar uma exceção de domínio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 65
    testRunner.And("a mensagem deve ser \"Não foi possível alterar a role do usuário. Verifique os dad" +
                        "os fornecidos.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar roles de um usuário com roles associadas")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Listar roles de um usuário com roles associadas")]
        public void ListarRolesDeUmUsuarioComRolesAssociadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar roles de um usuário com roles associadas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 71
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 72
    testRunner.And("o usuário possui 2 roles associadas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 73
    testRunner.When("eu listar as roles do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 74
    testRunner.Then("a listagem de roles do usuário deve retornar 2 roles", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 75
    testRunner.And("todas as roles devem pertencer ao usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar roles de um usuário sem roles associadas")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Listar roles de um usuário sem roles associadas")]
        public void ListarRolesDeUmUsuarioSemRolesAssociadas()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar roles de um usuário sem roles associadas", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 77
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 78
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 79
    testRunner.And("o usuário não possui roles associadas", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 80
    testRunner.When("eu listar as roles do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 81
    testRunner.Then("a listagem de roles do usuário deve retornar 0 roles", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao listar roles de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Roles de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao listar roles de usuário inexistente")]
        public void FalhaAoListarRolesDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao listar roles de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 84
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 85
    testRunner.When("eu listar as roles do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 86
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 87
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeRolesDeUsuarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeRolesDeUsuarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
