// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FIAPCloudGames.BDD.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeBibliotecaDeGamesFeature : object, Xunit.IClassFixture<GerenciamentoDeBibliotecaDeGamesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UsuarioGameBibliotecaAppService.feature"
#line hidden
        
        public GerenciamentoDeBibliotecaDeGamesFeature(GerenciamentoDeBibliotecaDeGamesFeature.FixtureData fixtureData, FIAPCloudGames_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Biblioteca de Games", "    Como um usuário do sistema\r\n    Eu quero gerenciar minha biblioteca de games\r" +
                    "\n    Para controlar os jogos que possuo", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
    testRunner.Given("que o serviço de biblioteca está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar biblioteca de um usuário com jogos")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Listar biblioteca de um usuário com jogos")]
        public void ListarBibliotecaDeUmUsuarioComJogos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar biblioteca de um usuário com jogos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 14
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 15
    testRunner.And("o usuário possui 2 jogos na biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.When("eu listar a biblioteca do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 17
    testRunner.Then("a listagem deve retornar 2 jogos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 18
    testRunner.And("todos os jogos devem pertencer ao usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar biblioteca de um usuário sem jogos")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Listar biblioteca de um usuário sem jogos")]
        public void ListarBibliotecaDeUmUsuarioSemJogos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar biblioteca de um usuário sem jogos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 21
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 22
    testRunner.And("o usuário não possui jogos na biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 23
    testRunner.When("eu listar a biblioteca do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 24
    testRunner.Then("a listagem deve retornar 0 jogos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao listar biblioteca de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao listar biblioteca de usuário inexistente")]
        public void FalhaAoListarBibliotecaDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao listar biblioteca de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 27
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 28
    testRunner.When("eu listar a biblioteca do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 29
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 30
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Comprar game com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Comprar game com sucesso")]
        public void ComprarGameComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Comprar game com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 35
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 36
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table23.AddRow(new string[] {
                            "TipoAquisicao",
                            "Compra"});
                table23.AddRow(new string[] {
                            "PrecoAquisicao",
                            "299.90"});
                table23.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-10"});
#line 37
    testRunner.And("tenho os dados da compra:", ((string)(null)), table23, "E ");
#line hidden
#line 42
    testRunner.When("eu comprar o game \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" para o usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 43
    testRunner.Then("a compra deve ser realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 44
    testRunner.And("o jogo deve estar na biblioteca do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao comprar game para usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao comprar game para usuário inexistente")]
        public void FalhaAoComprarGameParaUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao comprar game para usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 47
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 48
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table24.AddRow(new string[] {
                            "TipoAquisicao",
                            "Compra"});
                table24.AddRow(new string[] {
                            "PrecoAquisicao",
                            "299.90"});
                table24.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-10"});
#line 49
    testRunner.And("tenho os dados da compra:", ((string)(null)), table24, "E ");
#line hidden
#line 54
    testRunner.When("eu comprar o game \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" para o usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 55
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 56
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao comprar game inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao comprar game inexistente")]
        public void FalhaAoComprarGameInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao comprar game inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 59
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 60
    testRunner.And("não existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table25.AddRow(new string[] {
                            "TipoAquisicao",
                            "Compra"});
                table25.AddRow(new string[] {
                            "PrecoAquisicao",
                            "299.90"});
                table25.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-10"});
#line 61
    testRunner.And("tenho os dados da compra:", ((string)(null)), table25, "E ");
#line hidden
#line 66
    testRunner.When("eu comprar o game \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" para o usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 67
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 68
    testRunner.And("a mensagem deve conter \"Jogo com ID 2fa85f64-5717-4562-b3fc-2c963f66afa6 não enco" +
                        "ntrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao comprar game quando serviço retorna erro")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao comprar game quando serviço retorna erro")]
        public void FalhaAoComprarGameQuandoServicoRetornaErro()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao comprar game quando serviço retorna erro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 71
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 72
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 73
    testRunner.And("o serviço de biblioteca não consegue comprar o game", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table26.AddRow(new string[] {
                            "TipoAquisicao",
                            "Compra"});
                table26.AddRow(new string[] {
                            "PrecoAquisicao",
                            "299.90"});
                table26.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-10"});
#line 74
    testRunner.And("tenho os dados da compra:", ((string)(null)), table26, "E ");
#line hidden
#line 79
    testRunner.When("eu comprar o game \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" para o usuário \"3fa85f64" +
                        "-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 80
    testRunner.Then("a compra deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar item da biblioteca com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Atualizar item da biblioteca com sucesso")]
        public void AtualizarItemDaBibliotecaComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar item da biblioteca com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 84
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 85
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 86
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 87
    testRunner.And("existe um item na biblioteca com ID \"1fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table27.AddRow(new string[] {
                            "TipoAquisicao",
                            "Presente"});
                table27.AddRow(new string[] {
                            "PrecoAquisicao",
                            "0.00"});
                table27.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-15"});
#line 88
    testRunner.And("tenho os dados atualizados da biblioteca:", ((string)(null)), table27, "E ");
#line hidden
#line 93
    testRunner.When("eu atualizar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" da biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 94
    testRunner.Then("a atualização deve ser realizada com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 95
    testRunner.And("o item deve ter os dados atualizados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar item de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar item de usuário inexistente")]
        public void FalhaAoAtualizarItemDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar item de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 97
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 98
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 99
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table28.AddRow(new string[] {
                            "TipoAquisicao",
                            "Presente"});
                table28.AddRow(new string[] {
                            "PrecoAquisicao",
                            "0.00"});
                table28.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-15"});
#line 100
    testRunner.And("tenho os dados atualizados da biblioteca:", ((string)(null)), table28, "E ");
#line hidden
#line 105
    testRunner.When("eu atualizar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" da biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 106
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 107
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar item com game inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar item com game inexistente")]
        public void FalhaAoAtualizarItemComGameInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar item com game inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 110
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 111
    testRunner.And("não existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table29.AddRow(new string[] {
                            "TipoAquisicao",
                            "Presente"});
                table29.AddRow(new string[] {
                            "PrecoAquisicao",
                            "0.00"});
                table29.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-15"});
#line 112
    testRunner.And("tenho os dados atualizados da biblioteca:", ((string)(null)), table29, "E ");
#line hidden
#line 117
    testRunner.When("eu atualizar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" da biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 118
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 119
    testRunner.And("a mensagem deve conter \"Jogo com ID 2fa85f64-5717-4562-b3fc-2c963f66afa6 não enco" +
                        "ntrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar item inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar item inexistente")]
        public void FalhaAoAtualizarItemInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar item inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 121
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 122
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 123
    testRunner.And("existe um game com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 124
    testRunner.And("o item da biblioteca não existe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table30.AddRow(new string[] {
                            "TipoAquisicao",
                            "Presente"});
                table30.AddRow(new string[] {
                            "PrecoAquisicao",
                            "0.00"});
                table30.AddRow(new string[] {
                            "DataAquisicao",
                            "2024-01-15"});
#line 125
    testRunner.And("tenho os dados atualizados da biblioteca:", ((string)(null)), table30, "E ");
#line hidden
#line 130
    testRunner.When("eu atualizar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" da biblioteca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 131
    testRunner.Then("a atualização da biblioteca deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar item da biblioteca com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Deletar item da biblioteca com sucesso")]
        public void DeletarItemDaBibliotecaComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deletar item da biblioteca com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 135
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 136
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 137
    testRunner.And("existe um item na biblioteca com ID \"1fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 138
    testRunner.When("eu deletar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-571" +
                        "7-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 139
    testRunner.Then("o item deve ser deletado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar item de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar item de usuário inexistente")]
        public void FalhaAoDeletarItemDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar item de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 141
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 142
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 143
    testRunner.When("eu deletar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-571" +
                        "7-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 144
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 145
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar item inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Biblioteca de Games")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar item inexistente")]
        public void FalhaAoDeletarItemInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar item inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 147
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 148
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 149
    testRunner.And("o item da biblioteca não pode ser deletado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 150
    testRunner.When("eu deletar o item \"1fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-571" +
                        "7-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 151
    testRunner.Then("a exclusão da biblioteca deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeBibliotecaDeGamesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeBibliotecaDeGamesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
