// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FIAPCloudGames.BDD.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDePerfilDeUsuarioFeature : object, Xunit.IClassFixture<GerenciamentoDePerfilDeUsuarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UsuarioPerfilAppService.feature"
#line hidden
        
        public GerenciamentoDePerfilDeUsuarioFeature(GerenciamentoDePerfilDeUsuarioFeature.FixtureData fixtureData, FIAPCloudGames_BDD_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Perfil de Usuário", "    Como um usuário do sistema\r\n    Eu quero gerenciar meu perfil\r\n    Para mante" +
                    "r minhas informações pessoais atualizadas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 8
#line hidden
#line 9
    testRunner.Given("que o serviço de perfil está configurado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar perfil de usuário com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Buscar perfil de usuário com sucesso")]
        public void BuscarPerfilDeUsuarioComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar perfil de usuário com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 14
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 15
    testRunner.And("o usuário possui um perfil cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 16
    testRunner.When("eu buscar o perfil do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 17
    testRunner.Then("o perfil deve ser retornado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 18
    testRunner.And("o perfil deve conter as informações do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao buscar perfil de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao buscar perfil de usuário inexistente")]
        public void FalhaAoBuscarPerfilDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao buscar perfil de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 21
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 22
    testRunner.When("eu buscar o perfil do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 23
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 24
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao buscar perfil inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao buscar perfil inexistente")]
        public void FalhaAoBuscarPerfilInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao buscar perfil inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 27
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 28
    testRunner.And("o usuário não possui perfil cadastrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 29
    testRunner.When("eu buscar o perfil do usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 30
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 31
    testRunner.And("a mensagem deve conter \"Perfil para o usuário com ID 3fa85f64-5717-4562-b3fc-2c96" +
                        "3f66afa6 não encontrado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Cadastrar perfil com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Cadastrar perfil com sucesso")]
        public void CadastrarPerfilComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastrar perfil com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 36
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table31.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos"});
                table31.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table31.AddRow(new string[] {
                            "Pais",
                            "Brasil"});
                table31.AddRow(new string[] {
                            "AvatarUrl",
                            "https://avatar.url.jpg"});
#line 37
    testRunner.And("tenho os dados do perfil:", ((string)(null)), table31, "E ");
#line hidden
#line 43
    testRunner.When("eu cadastrar o perfil para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 44
    testRunner.Then("o perfil deve ser cadastrado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 45
    testRunner.And("o perfil retornado deve ter um ID válido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 46
    testRunner.And("o perfil deve conter os dados informados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao cadastrar perfil para usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao cadastrar perfil para usuário inexistente")]
        public void FalhaAoCadastrarPerfilParaUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao cadastrar perfil para usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 49
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table32.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos"});
                table32.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table32.AddRow(new string[] {
                            "Pais",
                            "Brasil"});
                table32.AddRow(new string[] {
                            "AvatarUrl",
                            "https://avatar.url.jpg"});
#line 50
    testRunner.And("tenho os dados do perfil:", ((string)(null)), table32, "E ");
#line hidden
#line 56
    testRunner.When("eu cadastrar o perfil para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 57
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 58
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para cadastrar o perfil\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao cadastrar perfil quando serviço retorna null")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao cadastrar perfil quando serviço retorna null")]
        public void FalhaAoCadastrarPerfilQuandoServicoRetornaNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao cadastrar perfil quando serviço retorna null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 61
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 62
    testRunner.And("o serviço de perfil não consegue cadastrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table33.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos"});
                table33.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table33.AddRow(new string[] {
                            "Pais",
                            "Brasil"});
                table33.AddRow(new string[] {
                            "AvatarUrl",
                            "https://avatar.url.jpg"});
#line 63
    testRunner.And("tenho os dados do perfil:", ((string)(null)), table33, "E ");
#line hidden
#line 69
    testRunner.When("eu cadastrar o perfil para o usuário \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 70
    testRunner.Then("deve lançar uma exceção de domínio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 71
    testRunner.And("a mensagem deve ser \"Não foi possível cadastrar o perfil. Verifique os dados forn" +
                        "ecidos ou se o usuário já possui um perfil.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar perfil com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Atualizar perfil com sucesso")]
        public void AtualizarPerfilComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar perfil com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 75
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 76
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 77
    testRunner.And("existe um perfil com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table34.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos Junior"});
                table34.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table34.AddRow(new string[] {
                            "Pais",
                            "Portugal"});
                table34.AddRow(new string[] {
                            "AvatarUrl",
                            "https://novo-avatar.url.jpg"});
#line 78
    testRunner.And("tenho os dados atualizados do perfil:", ((string)(null)), table34, "E ");
#line hidden
#line 84
    testRunner.When("eu atualizar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 85
    testRunner.Then("o perfil deve ser atualizado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 86
    testRunner.And("o perfil retornado deve ter os novos dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar perfil de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar perfil de usuário inexistente")]
        public void FalhaAoAtualizarPerfilDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar perfil de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 89
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table35.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos Junior"});
                table35.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table35.AddRow(new string[] {
                            "Pais",
                            "Portugal"});
                table35.AddRow(new string[] {
                            "AvatarUrl",
                            "https://novo-avatar.url.jpg"});
#line 90
    testRunner.And("tenho os dados atualizados do perfil:", ((string)(null)), table35, "E ");
#line hidden
#line 96
    testRunner.When("eu atualizar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 97
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 98
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para atualizar o perfil\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao atualizar perfil inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao atualizar perfil inexistente")]
        public void FalhaAoAtualizarPerfilInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao atualizar perfil inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 100
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 101
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 102
    testRunner.And("o perfil não existe", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table36.AddRow(new string[] {
                            "NomeCompleto",
                            "Marcio Silva Santos Junior"});
                table36.AddRow(new string[] {
                            "DataNascimento",
                            "1990-05-15"});
                table36.AddRow(new string[] {
                            "Pais",
                            "Portugal"});
                table36.AddRow(new string[] {
                            "AvatarUrl",
                            "https://novo-avatar.url.jpg"});
#line 103
    testRunner.And("tenho os dados atualizados do perfil:", ((string)(null)), table36, "E ");
#line hidden
#line 109
    testRunner.When("eu atualizar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 110
    testRunner.Then("a atualização do perfil deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar perfil com sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Deletar perfil com sucesso")]
        public void DeletarPerfilComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deletar perfil com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 114
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 115
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 116
    testRunner.And("existe um perfil com ID \"2fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 117
    testRunner.When("eu deletar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-5" +
                        "717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 118
    testRunner.Then("o perfil deve ser deletado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar perfil de usuário inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar perfil de usuário inexistente")]
        public void FalhaAoDeletarPerfilDeUsuarioInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar perfil de usuário inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 120
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 121
    testRunner.Given("que não existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 122
    testRunner.When("eu deletar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-5" +
                        "717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 123
    testRunner.Then("deve lançar uma exceção de não encontrado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 124
    testRunner.And("a mensagem deve conter \"Usuário com ID 3fa85f64-5717-4562-b3fc-2c963f66afa6 não e" +
                        "ncontrado para deletar o perfil\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Falha ao deletar perfil inexistente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Perfil de Usuário")]
        [Xunit.TraitAttribute("Description", "Falha ao deletar perfil inexistente")]
        public void FalhaAoDeletarPerfilInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao deletar perfil inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 126
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
this.FeatureBackground();
#line hidden
#line 127
    testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 128
    testRunner.And("o perfil não pode ser deletado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 129
    testRunner.When("eu deletar o perfil \"2fa85f64-5717-4562-b3fc-2c963f66afa6\" do usuário \"3fa85f64-5" +
                        "717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 130
    testRunner.Then("a exclusão do perfil deve falhar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDePerfilDeUsuarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDePerfilDeUsuarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
